config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :tasks
  end
  root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :name, :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_user, only: %i[new create destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = @user
    if @task.save
      redirect_to user_path(@user)
   else
    render :new, status: :unprocessable_entity
   end
  end

  def edit
    @user = User.find(params[:user_id])
    @task = @user.tasks.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @task = @user.tasks.find(params[:id])
    @task.update(task_params)

    redirect_to user_path(@user)
  end

  def destroy
    @task = Task.find(params[:id])

    @task.destroy

    redirect_to user_path(@user), status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def task_params
    params.require(:task).permit(:name, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to current_user, notice: 'You successfully update your profile.'}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700&family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/navbar" %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="container-flow nav-container">
  <div class="row">
    <div class="col-sm-12 col-md-10 col-lg-8 d-flex nav-items">
      <div class="col-6">
          <%= link_to root_path do %>
            <h3><strong>Task Manager</strong></h3>
          <% end %>
      </div>
      <div class="col-6 d-flex justify-content-end">
          <% if user_signed_in? %>
            <h5>Hello, <strong><%= current_user.name %></strong> !</h5>
            <%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete } %>
          <% else %>
            <%= link_to 'Login', new_user_session_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
          <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_task-form.html.erb
<%= simple_form_for [@user, @task] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :status, as: :select, collection: [['0', 'to-do'], ['1', 'doing'], ['2', 'done']], label_method: :second %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container forms-container">
  <div class="row d-flex justify-content-center">
    <div class="col-4">
      <h1>Edit Task</h1>
      <%= render "shared/task-form" %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<%# <h3>Hello <%= current_user %>

<%# <% @tasks.each do |task| %>
  <%# <h3><%= task.name %>
<%# <% end %> 

app/views/tasks/new.html.erb
<div class="container forms-container">
  <div class="row d-flex justify-content-center">
    <div class="col-4">
      <h1>New Task</h1>
      <%= render "shared/task-form" %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container main-container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 items-container">
      <div class="profile-container">
        <div class="profile-name">
          <h2><%= @task.name %></h2>
        </div>
        <h6 class="status-color <%=@task.status%>"><%= @task.status %></h6>
        <h3><%= @task.description %></h3>

    
        <%= link_to 'Back to list', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container forms-container">
  <div class="row d-flex justify-content-center">
    <div class="col-4">
      <h1>Edit Profile</h1>

      <%= simple_form_for @user do |f| %>
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container main-container">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-10 col-lg-8 items-container">
        <% @users.each do |user| %>
          <div class="index-user">
            <%= link_to user_path(user) do %>
              <h3><%= user.name %></h3>
            <% end %>
            <h5><%= user.tasks.count %></h5>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container main-container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 items-container">
      <div class="profile-container">
        <div class="profile-name">
          <h1><%= @user.name %></h1>
        </div>
        <div class="profile-links">
          <% if current_user.id == @user.id %>
            <%= link_to 'Edit profile', edit_user_path(current_user) %>
          <% end %> |
          <%= link_to "Delete user",
            user_path(@user),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </div>
      </div>

      <% if current_user.id == @user.id %>
        <div class="btn-new">
          <%= link_to 'New Task', new_user_task_path(@user) %>
        </div>
      <% end %>

      <div class="tasks-list">
        <% @user.tasks.each do |task| %>
          <ul class="list-group-item">
            <%= link_to user_task_path(@user, task) do %>
              <h5><%= task.name %></h5>
            <% end %>
            <div class="show-icons">
                <h6 class="status-color <%=task.status%>"><%= task.status %></h6>
                <% if current_user.id == @user.id %>
                  <%= link_to edit_user_task_path(@user, task) do %>
                    <i class="fa-solid fa-pen-to-square"></i>
                  <% end %>
                  <%= link_to user_task_path(@user, task),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, remote: true do %>
                    <i class="fa-solid fa-trash"></i>
                  <% end %>
                <% end %>
            </div>
          </ul>
        <% end %>
      </div>
      <br>

      <%= link_to 'Back to List', root_path %>
    </div>
  </div>
</div>